package com.stockpulse.model;

import lombok.Builder;
import lombok.Data;

/**
 * Real-time alert generated by Module 9 — Alert Engine.
 */
@Data
@Builder
public class StockAlert {
    private String stockSymbol;
    private String reason;
    private double confidenceScore;
    private String timestamp;
    private String alertType; // RALLY / NEWS / SENTIMENT / VOLUME / AI_PREDICTION / INSTITUTIONAL
    private String severity;  // HIGH / MEDIUM / LOW
}
